version: '3'
services:
  backend:
    image: fullstack-code-test/backend:latest
    build: backend
    environment:
     - DB_HOST=database
    depends_on:
      - database
    links:
     - "database"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 9090:9090
    command: ["./wait-for-it.sh", "database:5432", "--", "npm", "start"]

  frontend:
    image: fullstack-code-test/frontend:latest
    build: frontend
    links:
     - "backend"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    command: ["npm", "start"]

  database:
    image: "postgres:11"
    env_file:
    - ./db/localdb.env
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5432:5432